import { boolean, bigint, int, mysqlEnum, mysqlTable, text, timestamp, varchar, json } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
  /** Stripe customer ID — set when user initiates first checkout */
  stripeCustomerId: varchar("stripeCustomerId", { length: 255 }),
  /** Stripe subscription ID — set after checkout.session.completed webhook */
  stripeSubscriptionId: varchar("stripeSubscriptionId", { length: 255 }),
  /** Subscription tier: free | pro */
  subscriptionTier: mysqlEnum("subscriptionTier", ["free", "pro"]).default("free").notNull(),
  /** When the current subscription period ends (from Stripe) */
  subscriptionEndsAt: timestamp("subscriptionEndsAt"),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/** Waitlist signups — captured before full auth */
export const waitlist = mysqlTable("waitlist", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  company: varchar("company", { length: 255 }),
  role: varchar("role", { length: 255 }),
  agentCount: varchar("agentCount", { length: 64 }),
  source: varchar("source", { length: 64 }).default("website"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type WaitlistEntry = typeof waitlist.$inferSelect;
export type InsertWaitlistEntry = typeof waitlist.$inferInsert;

/** Audit tool submissions — track every compliance audit run */
export const auditSubmissions = mysqlTable("auditSubmissions", {
  id: int("id").autoincrement().primaryKey(),
  agentType: varchar("agentType", { length: 64 }).notNull(),
  useCase: varchar("useCase", { length: 255 }).notNull(),
  dataSources: text("dataSources"),
  irreversibleDecisions: boolean("irreversibleDecisions").default(false),
  processesPersonalData: boolean("processesPersonalData").default(false),
  hasAuditTrail: boolean("hasAuditTrail").default(false),
  overallScore: int("overallScore"),
  riskLevel: mysqlEnum("riskLevel", ["HIGH", "LIMITED", "MINIMAL"]),
  userId: int("userId"),
  ipHash: varchar("ipHash", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AuditSubmission = typeof auditSubmissions.$inferSelect;
export type InsertAuditSubmission = typeof auditSubmissions.$inferInsert;

/**
 * Agent decision traces — the core product table.
 * Every time an instrumented agent makes a decision, a record lands here.
 * This is what the SDK writes to via POST /api/v1/decisions.
 */
export const agentDecisions = mysqlTable("agentDecisions", {
  id: int("id").autoincrement().primaryKey(),
  /** Unique ID for this decision — generated by SDK or caller */
  decisionId: varchar("decisionId", { length: 128 }).notNull().unique(),
  /** Which agent made this decision */
  agentId: varchar("agentId", { length: 128 }).notNull(),
  agentVersion: varchar("agentVersion", { length: 64 }),
  /** The entity this decision was about (customer ID, user ID, case ID etc.) */
  subjectId: varchar("subjectId", { length: 255 }),
  subjectType: varchar("subjectType", { length: 64 }),
  /** What the agent was asked to do */
  useCase: varchar("useCase", { length: 255 }).notNull(),
  /** Summary of input data (not raw data — a description or hash) */
  inputSummary: text("inputSummary"),
  /** SHA-256 hash of the raw input for integrity verification */
  inputHash: varchar("inputHash", { length: 64 }),
  /** What the agent decided */
  outputSummary: text("outputSummary").notNull(),
  /** Structured output if available */
  outputData: json("outputData").$type<Record<string, unknown> | null>(),
  /** Which data sources were used (array of source names/URIs) */
  dataSources: json("dataSources").$type<string[] | null>(),
  /** Which LLM or model was invoked */
  modelName: varchar("modelName", { length: 128 }),
  modelVersion: varchar("modelVersion", { length: 64 }),
  /** EU AI Act risk classification */
  riskClassification: mysqlEnum("riskClassification", ["HIGH", "LIMITED", "MINIMAL", "UNCLASSIFIED"]).default("UNCLASSIFIED"),
  /** Latency in milliseconds */
  latencyMs: int("latencyMs"),
  /** Confidence score 0-100 if the model provides one */
  confidenceScore: int("confidenceScore"),
  /** API key used to submit this decision (links to an org/project) */
  apiKeyHash: varchar("apiKeyHash", { length: 64 }),
  /** Owner user ID (if submitted via authenticated session) */
  userId: int("userId"),
  /** When the decision was made (UTC ms) — set by the SDK */
  decidedAt: bigint("decidedAt", { mode: "number" }).notNull(),
  /** When we received it */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AgentDecision = typeof agentDecisions.$inferSelect;
export type InsertAgentDecision = typeof agentDecisions.$inferInsert;

/** API keys — allow SDK users to submit decisions without Manus OAuth */
export const apiKeys = mysqlTable("apiKeys", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  keyHash: varchar("keyHash", { length: 64 }).notNull().unique(),
  keyPrefix: varchar("keyPrefix", { length: 12 }).notNull(),
  name: varchar("name", { length: 128 }).notNull(),
  isActive: boolean("isActive").default(true).notNull(),
  lastUsedAt: timestamp("lastUsedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ApiKey = typeof apiKeys.$inferSelect;
export type InsertApiKey = typeof apiKeys.$inferInsert;
